// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package db

import (
	"database/sql"
	"time"
)

type Transaction struct {
	ID              int64          `json:"id"`
	UserID          sql.NullInt64  `json:"user_id"`
	Amount          int64          `json:"amount"`
	TransactionType sql.NullString `json:"transaction_type"`
	CreatedAt       time.Time      `json:"created_at"`
}

type User struct {
	ID        int64     `json:"id"`
	Firstname string    `json:"firstname"`
	Lastname  string    `json:"lastname"`
	Username  string    `json:"username"`
	Email     string    `json:"email"`
	Password  string    `json:"-"`
	Balance   int64     `json:"balance"`
	CreatedAt time.Time `json:"created_at"`
}
