// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0
// source: transaction.sql

package db

import (
	"context"
)

const createTransaction = `-- name: CreateTransaction :one
INSERT INTO transactions (
    user_id, amount, transaction_type, username
) VALUES (
  $1, $2 , $3 , $4
)
RETURNING id, user_id, username, amount, transaction_type, created_at
`

type CreateTransactionParams struct {
	UserID          int64  `json:"user_id"`
	Amount          int32  `json:"amount"`
	TransactionType string `json:"transaction_type"`
	Username        string `json:"username"`
}

func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error) {
	row := q.db.QueryRowContext(ctx, createTransaction,
		arg.UserID,
		arg.Amount,
		arg.TransactionType,
		arg.Username,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Username,
		&i.Amount,
		&i.TransactionType,
		&i.CreatedAt,
	)
	return i, err
}

const getTransaction = `-- name: GetTransaction :one
SELECT id, user_id, username, amount, transaction_type, created_at FROM transactions
WHERE user_id = $1
AND transaction_type = $2
`

type GetTransactionParams struct {
	UserID          int64  `json:"user_id"`
	TransactionType string `json:"transaction_type"`
}

func (q *Queries) GetTransaction(ctx context.Context, arg GetTransactionParams) (Transaction, error) {
	row := q.db.QueryRowContext(ctx, getTransaction, arg.UserID, arg.TransactionType)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Username,
		&i.Amount,
		&i.TransactionType,
		&i.CreatedAt,
	)
	return i, err
}

const getTransactionsByUsername = `-- name: GetTransactionsByUsername :many
SELECT id, user_id, username, amount, transaction_type, created_at FROM transactions
WHERE username = $1
`

func (q *Queries) GetTransactionsByUsername(ctx context.Context, username string) ([]Transaction, error) {
	rows, err := q.db.QueryContext(ctx, getTransactionsByUsername, username)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Transaction
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Username,
			&i.Amount,
			&i.TransactionType,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
